version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: wazmeow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: wazmeow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wazmeow-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d wazmeow"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: wazmeow-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass redispassword
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - wazmeow-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # DBGate - Database Administration Tool
  dbgate:
    image: dbgate/dbgate:latest
    container_name: wazmeow-dbgate
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      CONNECTIONS: con1,con2
      LABEL_con1: PostgreSQL
      SERVER_con1: postgres
      USER_con1: postgres
      PASSWORD_con1: password
      PORT_con1: 5432
      ENGINE_con1: postgres@dbgate-plugin-postgres
      LABEL_con2: Redis
      URL_con2: redis://redis:6379
      ENGINE_con2: redis@dbgate-plugin-redis
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - wazmeow-network





volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  wazmeow-network:
    driver: bridge
